# Global configs
global:
  orgName: "<your org name on Braintrust>"
  namespace: "braintrust"

# Cloud provider configuration
cloud: "aws"  # or "azure"

# Object storage configuration
objectStorage:
  # Azure specific configuration
  azure:
    storageAccountName: ""  # Azure storage account name
    brainstoreContainer: "brainstore"  # Azure container name for brainstore
    responseContainer: "responses"  # Azure container name for responses
    codeBundleContainer: "code-bundles"  # Azure container name for code bundles

  # AWS specific configuration
  aws:
    brainstoreBucket: ""  # S3 bucket name for brainstore
    responseBucket: "responses"  # S3 bucket name for responses
    codeBundleBucket: "code-bundles"  # S3 bucket name for code bundles

api:
  name: "braintrust-api"
  replicas: 2
  image:
    repository: public.ecr.aws/braintrust/standalone-api
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests:
      cpu: "2"
      memory: "4Gi"
    limits:
      cpu: "4"
      memory: "8Gi"
  # Allow running user generated code functions (e.g. scorers/tools)
  allowCodeFunctionExecution: true
  # Brainstore backfill configuration
  enableHistoricalFullBackfill: true
  backfillNewObjects: true
  backfillDisableHistorical: false
  backfillDisableNonhistorical: false
  extraEnvVars:
    # Example:
    # - name: MY_ENV_VAR
    #   value: "my-value"
    # - name: ANOTHER_VAR
    #   value: "another-value"

# Brainstore configuration
brainstore:
  name: "brainstore"
  replicas: 1
  image:
    repository: public.ecr.aws/braintrust/brainstore
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 4000
  resources:
    requests:
      cpu: "8"
      memory: "16Gi"
    limits:
      cpu: "16"
      memory: "32Gi"
  cacheDir: "/mnt/tmp/brainstore"
  objectStoreCacheMemoryLimit: "1Gi"
  objectStoreCacheFileSize: "50Gi"
  verbose: true
  noColor: true
  extraEnvVars:
    # Example:
    # - name: MY_ENV_VAR
    #   value: "my-value"
    # - name: ANOTHER_VAR
    #   value: "another-value"

