apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service.name | default .Values.api.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "apps.service-labels" (dict "context" . "service" .Values.api) | nindent 4 }}
  {{- with .Values.api.annotations.service }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ .Values.api.name }}
  ports:
    - name: {{ .Values.api.service.portName }}
      protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
  type: {{ .Values.api.service.type }}
