apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.service.port }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.api.name }}
          env:
            - name: PG_URL
              valueFrom:
                secretKeyRef:
                  name: braintrust-secrets
                  key: PG_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: braintrust-secrets
                  key: REDIS_URL
            - name: FUNCTION_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: braintrust-secrets
                  key: FUNCTION_SECRET_KEY
            {{- if eq .Values.cloud "azure" }}
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: braintrust-secrets
                  key: AZURE_STORAGE_CONNECTION_STRING
            {{- end }}
            {{- if .Values.api.extraEnvVars }}
            {{- toYaml .Values.api.extraEnvVars | nindent 12 }}
            {{- end }}

