apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.brainstore.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.brainstore.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.brainstore.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.brainstore.name }}
    spec:
      containers:
        - name: brainstore
          image: "{{ .Values.brainstore.image.repository }}:{{ .Values.brainstore.image.tag }}"
          imagePullPolicy: {{ .Values.brainstore.image.pullPolicy }}
          command: "web"
          ports:
            - containerPort: {{ .Values.brainstore.service.port }}
          resources:
            {{- toYaml .Values.brainstore.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.brainstore.name }}
          env:
            - name: BRAINSTORE_METADATA_URI
              valueFrom:
                secretKeyRef:
                  name: braintrust-secrets
                  key: PG_URL
            - name: BRAINSTORE_WAL_URI
              valueFrom:
                secretKeyRef:
                  name: braintrust-secrets
                  key: PG_URL
            - name: BRAINSTORE_LOCKS_URI
              valueFrom:
                secretKeyRef:
                  name: braintrust-secrets
                  key: REDIS_URL
            - name: BRAINSTORE_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: braintrust-secrets
                  key: BRAINSTORE_LICENSE_KEY
            {{- if eq .Values.cloud "azure" }}
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: braintrust-secrets
                  key: AZURE_STORAGE_CONNECTION_STRING
            {{- end }}
            {{- if .Values.brainstore.extraEnvVars }}
            {{- toYaml .Values.brainstore.extraEnvVars | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: cache-volume
              mountPath: {{ .Values.brainstore.cacheDir }}
      volumes:
        - name: cache-volume
          emptyDir:
            sizeLimit: {{ .Values.brainstore.cacheSizeLimit | quote }}
